// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudOperation.Models
{
    public partial class AllEmployeeResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public string skill { get; set; }
        public string address { get; set; }
        public bool? isactive { get; set; }
    }
}
