// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudOperation.Models
{
    public partial class GetAllEmployeesWithSkillsResult
    {
        public int EmployeeId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
    }
}
