// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudOperation.Models;

public partial class Skill
{
    public int Id { get; set; }
   
    public string Title { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}