// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudOperation.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public bool? Isactive { get; set; }

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}